name: workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: helloworld
        run: echo "heelo word"
        shell: bash
  
  good bye:
    runs-on: ubuntu-latest
    steps:
      - name: godbye world
        run: echo "goodbye word"
        shell: bash
